title: "The Distillation 'Heist' Is Quietly Powering American AI"
description: "A response to Foreign Affairs' 'China's AI Heist'. Maybe a hot take, but just think and it's not hard to see that Qwen supports American Capitalism. Chinese checkpoints protect consumers via open-source, American competition, while distillation has extended the dominance of American AI."
theme: jekyll-theme-minimal
markdown: kramdown
